export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const UPDATE_QUERY = 'UPDATE_QUERY';

export const SEARCH = 'SEARCH';
export const RECEIVE_RESULTS = 'RECEIVE_RESULTS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const SEARCH_COMMENTS = 'SEARCH_COMMENTS';
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS';
export const SEARCH_COMMENTS_ERROR = 'SEARCH_COMMENTS_ERROR';

export const SEARCH_STATS = 'SEARCH_STATS';
export const RECEIVE_STATS = 'RECEIVE_STATS';
export const SEARCH_STATS_ERROR = 'SEARCH_STATS_ERROR';

export const SUGGEST = 'SUGGEST';

export const CREATE_FAVORITE_REQUEST = 'CREATE_FAVORITE_REQUEST';
export const CREATE_FAVORITE_FAILURE = 'CREATE_FAVORITE_FAILURE';
export const CREATE_FAVORITE_SUCCESS = 'CREATE_FAVORITE_SUCCESS';
export const GET_FAVORITES = 'GET_FAVORITES';
export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_FAILURE = 'GET_FAVORITES_FAILURE';
export const DESTROY_FAVORITE = 'DESTROY_FAVORITE';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
